import { StyleSheet, Dimensions, Platform } from 'react-native';
import { colors, radius, shadow, spacing, typography } from '../lib/theme';

export const { width: screenW, height: screenH } = Dimensions.get('window');

export const styles = StyleSheet.create({
  scrollGrow: { flexGrow: 1 },
  safeAreaZero: { flex: 1 },

  // Added luxury components styles
  heroSubDescBilingual: {
    fontSize: 10,
    color: 'rgba(0, 0, 0, 0.65)',
    fontWeight: '600',
    marginTop: 4,
  },
  heroArrowWrap: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  statBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  statSubTextLabel: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 2,
  },
  gamePlayCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(236, 200, 122, 0.15)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  splashLogoOuterBorder: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 2.5,
    borderColor: 'rgba(236, 200, 122, 0.45)', // outer gold ring
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.lg,
    backgroundColor: 'rgba(236, 200, 122, 0.03)',
  },
  splashLogoInnerBorder: {
    width: 146,
    height: 146,
    borderRadius: 73,
    borderWidth: 1.5,
    borderColor: '#ECC87A', // inner hairline gold ring
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Splash styling
  splashContainer: {
    flex: 1,
    backgroundColor: colors.background,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.xxl,
  },
  splashGraphicWrap: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  tourbillonBackground: {
    position: 'absolute',
    alignSelf: 'center',
  },
  splashIconOutline: {
    width: 96,
    height: 96,
    borderRadius: 48,
    borderWidth: 2,
    borderColor: 'rgba(236, 200, 122, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.xl,
    backgroundColor: 'rgba(236, 200, 122, 0.05)',
  },
  splashLogoImage: {
    width: 140,
    height: 140,
    borderRadius: 70,
    borderWidth: 2.5,
    borderColor: 'rgba(236, 200, 122, 0.65)',
    marginBottom: spacing.lg,
    backgroundColor: '#0A0806',
  },
  crownDot: {
    position: 'absolute',
    top: 10,
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: colors.amber,
  },
  splashTitle: {
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    fontSize: 40,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 4,
    lineHeight: 48,
  },
  splashSubtitle: {
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    fontSize: 14,
    fontWeight: '700',
    color: colors.amber,
    letterSpacing: 8,
    marginTop: spacing.xs,
    lineHeight: 18,
  },
  splashDivider: {
    width: 48,
    height: 2,
    backgroundColor: 'rgba(236, 200, 122, 0.35)',
    marginVertical: spacing.lg,
  },
  splashDescription: {
    ...typography.caption,
    color: colors.textSecondary,
    textAlign: 'center',
    paddingHorizontal: spacing.xl,
  },
  splashFooter: {
    alignItems: 'center',
    gap: spacing.sm,
  },
  splashFooterText: {
    ...typography.small,
    color: colors.textMuted,
    letterSpacing: 1.5,
  },

  loginLogoOuterBorder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    borderWidth: 2,
    borderColor: 'rgba(236, 200, 122, 0.45)', // outer gold ring
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
    backgroundColor: 'rgba(236, 200, 122, 0.03)',
    position: 'relative',
  },
  loginLogoInnerBorder: {
    width: 88,
    height: 88,
    borderRadius: 44,
    borderWidth: 1.5,
    borderColor: '#ECC87A', // inner hairline gold ring
    justifyContent: 'center',
    alignItems: 'center',
  },
  loginPremiumBtn: {
    height: 52,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.md,
    overflow: 'hidden',
  },
  loginPremiumBtnText: {
    color: '#0A0805', // dark premium text color
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 2,
  },

  // Login styling
  loginContainer: {
    flex: 1,
    backgroundColor: colors.background,
  },
  loginContent: {
    padding: spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: screenH - 80,
  },
  loginHeader: {
    alignItems: 'center',
    marginBottom: spacing.xxl,
  },
  loginLogo: {
    marginBottom: spacing.md,
  },
  loginLogoContainer: {
    width: 80,
    height: 80,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: spacing.md,
    position: 'relative',
  },
  monogramWrap: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  monogramText: {
    fontSize: 10,
    fontWeight: '900',
    color: colors.amber,
    marginTop: 2,
  },
  loginTitle: {
    ...typography.h1,
    marginBottom: spacing.xs,
  },
  loginSubtitle: {
    ...typography.caption,
    fontWeight: '800',
    color: colors.amber,
    letterSpacing: 2,
    textAlign: 'center',
  },
  loginSubDesc: {
    ...typography.caption,
    textAlign: 'center',
    paddingHorizontal: spacing.md,
    marginTop: spacing.xs,
  },
  loginCard: {
    backgroundColor: colors.surface,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    width: '100%',
    gap: spacing.md,
    ...shadow.md,
  },
  inputLabel: {
    ...typography.bodyBold,
    color: colors.textSecondary,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.backgroundElevated,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: spacing.md,
    height: 48,
  },
  inputIcon: { marginRight: spacing.sm },
  textInput: {
    flex: 1,
    color: '#fff',
    fontSize: 15,
  },
  loginBtn: {
    backgroundColor: colors.amber,
    height: 48,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.sm,
  },
  loginBtnText: {
    color: '#000',
    fontSize: 16,
    fontWeight: '700',
  },
  orText: {
    ...typography.caption,
    color: colors.textMuted,
    marginVertical: spacing.xl,
  },
  presetGrid: {
    flexDirection: 'row',
    gap: spacing.md,
    width: '100%',
  },
  presetCard: {
    flex: 1,
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    gap: spacing.xs,
  },
  presetEmoji: { fontSize: 24 },
  presetName: {
    ...typography.bodyBold,
    fontSize: 14,
  },
  presetEmail: {
    ...typography.caption,
    fontSize: 11,
    color: colors.textMuted,
  },

  // Home styling
  homeContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  homeContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
  },
  homeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.md,
  },
  greeting: {
    ...typography.h2,
  },
  headerSub: {
    ...typography.caption,
  },
  membershipBadge: {
    backgroundColor: colors.goldLight,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: colors.amber,
  },
  membershipBadgeText: {
    color: colors.amber,
    fontSize: 11,
    fontWeight: '800',
  },
  heroCard: {
    backgroundColor: colors.amber,
    padding: spacing.lg,
    borderRadius: radius.lg,
    marginTop: spacing.sm,
    overflow: 'hidden',
    ...shadow.amber,
  },
  heroGlow: {
    position: 'absolute',
    right: -20,
    top: -20,
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  heroTextContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  heroIconWrap: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#000',
    lineHeight: 24,
  },
  heroDesc: {
    fontSize: 12,
    color: 'rgba(0,0,0,0.65)',
    lineHeight: 16,
    fontWeight: '600',
    marginTop: 2,
  },
  statsCard: {
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionTitle: {
    ...typography.bodyBold,
    marginBottom: spacing.md,
  },
  statsGrid: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  statBox: {
    flex: 1,
    backgroundColor: colors.backgroundElevated,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statLabel: {
    ...typography.caption,
    color: colors.textMuted,
  },
  statValue: {
    ...typography.h3,
    marginTop: spacing.xs,
  },
  statSubText: {
    ...typography.small,
    marginTop: 2,
  },
  miniGameCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(236, 200, 122, 0.08)',
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(236, 200, 122, 0.2)',
    padding: spacing.md,
  },
  gameTextWrap: { flex: 1 },
  gameTitle: {
    ...typography.bodyBold,
    color: colors.amber,
  },
  gameDesc: {
    ...typography.caption,
    fontSize: 12,
    marginTop: 2,
  },
  subSectionHeader: {
    ...typography.bodyBold,
    color: colors.textSecondary,
    marginTop: spacing.sm,
  },
  verticalBrandListContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
    marginTop: spacing.sm,
  },
  brandColumn: {
    flex: 1,
    gap: 6,
  },
  verticalBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md - 2,
    paddingVertical: spacing.xs + 2,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: 'rgba(236, 200, 122, 0.18)',
    elevation: 2,
    shadowColor: colors.amber,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
  },
  brandRowInner: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  brandRowText: {
    color: '#FFF',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  brandRowStatus: {
    color: colors.amber,
    fontSize: 8,
    fontWeight: '800',
    letterSpacing: 0.5,
    opacity: 0.8,
  },

  // Collection styling
  collectionContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  colHeaderCard: {
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  colHeaderTitle: {
    ...typography.h2,
    marginBottom: spacing.xs,
  },
  colSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: spacing.sm,
  },
  colSummaryLabel: {
    ...typography.caption,
    color: colors.textMuted,
  },
  colSummaryValue: {
    ...typography.h3,
  },
  filterTabsRow: {
    flexDirection: 'row',
    padding: spacing.md,
    gap: spacing.sm,
  },
  filterTab: {
    flex: 1,
    height: 38,
    borderRadius: radius.md,
    backgroundColor: colors.surface,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterTabActive: {
    backgroundColor: colors.amber,
    borderColor: colors.amber,
  },
  filterTabText: {
    color: colors.textSecondary,
    fontSize: 13,
    fontWeight: '700',
  },
  filterTabTextActive: {
    color: '#000',
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xxl,
    gap: spacing.md,
    minHeight: 300,
  },
  emptyText: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: 'center',
  },
  emptyBtn: {
    backgroundColor: colors.surfaceMuted,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emptyBtnText: {
    color: colors.amber,
    fontWeight: '700',
  },
  colListScroll: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
  },
  watchItemCard: {
    flexDirection: 'row',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    gap: spacing.md,
    position: 'relative',
    ...shadow.sm,
  },
  watchItemImg: {
    width: 80,
    height: 80,
    borderRadius: radius.md,
    backgroundColor: colors.background,
  },
  watchItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  watchItemBrand: {
    ...typography.caption,
    color: colors.amber,
    fontWeight: '700',
  },
  watchItemName: {
    ...typography.bodyBold,
    fontSize: 16,
    paddingRight: 24,
  },
  watchItemReference: {
    ...typography.small,
    color: colors.textMuted,
  },
  watchItemFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: spacing.xs,
    flexWrap: 'wrap',
    gap: 6,
  },
  verdictBadgeText: {
    fontSize: 12,
    fontWeight: '700',
  },
  watchItemPrice: {
    ...typography.bodyBold,
    color: '#fff',
  },
  deleteItemBtn: {
    position: 'absolute',
    top: spacing.md,
    right: spacing.md,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(239, 68, 68, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  soldBadge: {
    backgroundColor: colors.successLight,
    paddingHorizontal: spacing.xs,
    paddingVertical: 1,
    borderRadius: radius.sm,
  },
  soldBadgeText: {
    color: colors.success,
    fontSize: 9,
    fontWeight: '800',
  },

  // Portfolio styling
  portContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  portContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
  },
  portTitle: {
    ...typography.h2,
    marginTop: spacing.md,
  },
  roiCard: {
    backgroundColor: colors.surface,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  roiLabel: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  roiValue: {
    fontSize: 36,
    fontWeight: '900',
    color: colors.success,
    marginVertical: spacing.xs,
  },
  roiDelta: {
    ...typography.small,
    color: colors.textMuted,
  },
  roiGrid: {
    flexDirection: 'row',
    gap: spacing.lg,
    marginTop: spacing.lg,
    width: '100%',
  },
  roiBox: {
    flex: 1,
    backgroundColor: colors.backgroundElevated,
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
  },
  roiBoxLabel: {
    ...typography.small,
    color: colors.textMuted,
  },
  roiBoxVal: {
    ...typography.bodyBold,
    fontSize: 16,
    marginTop: 4,
  },
  diversificationCard: {
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.md,
  },
  diverRow: {
    gap: spacing.xs,
  },
  diverHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  diverName: {
    ...typography.bodyBold,
  },
  diverCount: {
    ...typography.caption,
  },
  progressBarBg: {
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.backgroundElevated,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.amber,
    borderRadius: 4,
  },
  emptyProgressText: {
    ...typography.body,
    color: colors.textMuted,
    textAlign: 'center',
    paddingVertical: spacing.md,
  },
  graphWrap: {
    flexDirection: 'row',
    height: 180,
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    marginTop: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  graphBar: {
    width: 28,
    height: 40,
    backgroundColor: colors.backgroundElevated,
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
  },
  graphMonthsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.md,
    marginTop: spacing.sm,
  },
  graphMonthText: {
    fontSize: 11,
    color: colors.textMuted,
    fontWeight: '600',
  },

  // Settings styling
  settingsContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  settingsContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
  },
  settingsTitle: {
    ...typography.h2,
    marginTop: spacing.md,
  },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  profileAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: colors.amber,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarEditOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.65)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarText: {
    color: '#000',
    fontWeight: '900',
    fontSize: 18,
  },
  profileName: {
    ...typography.bodyBold,
    fontSize: 18,
  },
  profileEmail: {
    ...typography.caption,
    color: colors.textMuted,
  },
  planCard: {
    backgroundColor: colors.surface,
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    gap: spacing.xs,
  },
  planHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  planTitle: {
    ...typography.caption,
    color: colors.textSecondary,
  },
  planTier: {
    fontSize: 16,
    fontWeight: '900',
  },
  planDetails: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 14,
    lineHeight: 20,
    marginTop: spacing.xs,
  },
  planUpgradeBtn: {
    backgroundColor: colors.surfaceMuted,
    height: 42,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: spacing.sm,
  },
  planUpgradeText: {
    color: colors.amber,
    fontWeight: '700',
  },
  settingsMenu: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: spacing.sm,
  },
  menuItemText: {
    flex: 1,
    ...typography.bodyBold,
    fontSize: 14,
  },
  logoutBtn: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: spacing.sm,
    backgroundColor: colors.danger,
    height: 48,
    borderRadius: radius.md,
  },
  logoutText: {
    color: '#fff',
    fontWeight: '700',
  },

  // Dev bar overlay
  devCard: {
    backgroundColor: '#1E120A',
    borderRadius: radius.lg,
    borderWidth: 2,
    borderColor: colors.amber,
    padding: spacing.md,
    gap: spacing.md,
    marginTop: spacing.lg,
  },
  devCardTitle: {
    color: colors.amber,
    fontWeight: '900',
    fontSize: 14,
    textAlign: 'center',
  },
  devCardSub: {
    color: colors.textSecondary,
    fontSize: 11,
    textAlign: 'center',
    lineHeight: 16,
  },
  devBtnRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  devTierBtn: {
    flex: 1,
    height: 32,
    borderRadius: radius.sm,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  devTierBtnActive: {
    backgroundColor: colors.amber,
    borderColor: colors.amber,
  },
  devTierText: {
    color: colors.textSecondary,
    fontSize: 10,
    fontWeight: '800',
  },
  devTierTextActive: {
    color: '#000',
  },
  devActionRow: {
    flexDirection: 'column',
    gap: spacing.sm,
  },
  devActionBtn: {
    width: '100%',
    height: 42,
    borderRadius: radius.md,
    backgroundColor: 'rgba(236, 200, 122, 0.08)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(236, 200, 122, 0.25)',
    paddingHorizontal: spacing.sm,
  },
  devActionText: {
    color: colors.amber,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },

  // Upgrade / Membership Styling
  upgradeContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  upgradeContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
  },
  upgradeHeader: {
    alignItems: 'center',
    marginVertical: spacing.md,
    position: 'relative',
  },
  upgradeClose: {
    position: 'absolute',
    left: 0,
    top: 4,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  upgradeTitle: {
    ...typography.h1,
    marginTop: spacing.sm,
  },
  upgradeSubtitle: {
    ...typography.caption,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  tierOptionCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.lg,
    borderRadius: radius.lg,
    gap: spacing.md,
    position: 'relative',
  },
  tierOptionCardBest: {
    borderColor: colors.amber,
    borderWidth: 2,
    backgroundColor: '#1C160F',
    ...shadow.amber,
  },
  recommendedBadge: {
    position: 'absolute',
    top: -12,
    right: 20,
    backgroundColor: colors.amber,
    paddingHorizontal: spacing.md,
    paddingVertical: 2,
    borderRadius: radius.sm,
  },
  recommendedText: {
    color: '#000',
    fontSize: 11,
    fontWeight: '800',
  },
  tierBadgeWrap: {
    marginBottom: 12,
  },
  tierHeaderTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  tierName: {
    fontSize: 18,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 0.5,
  },
  tierPriceSection: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: 4,
  },
  tierPrice: {
    fontSize: 28,
    fontWeight: '900',
    color: '#fff',
  },
  tierPriceUnit: {
    fontSize: 14,
    color: colors.textSecondary,
    marginLeft: 4,
    fontWeight: '600',
  },
  tierDailyEst: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 2,
  },
  featuresList: {
    gap: 8,
    marginVertical: 12,
  },
  featureRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  featureIcon: {
    marginTop: 2,
  },
  featureText: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
    flex: 1,
  },
  tierBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 12,
    borderWidth: 1,
  },
  tierBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  tierDetails: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.textSecondary,
  },
  tierActionBtn: {
    backgroundColor: colors.surfaceMuted,
    height: 44,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  tierActionBtnBest: {
    backgroundColor: colors.amber,
    borderColor: colors.amber,
  },
  tierActionBtnActive: {
    opacity: 0.5,
  },
  tierActionBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 14,
  },
  tierPriceThai: {
    marginTop: -4,
  },
  creditPacksContainer: {
    gap: spacing.md,
    marginTop: spacing.xl,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  creditPackCard: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    borderRadius: radius.md,
    gap: spacing.sm,
    position: 'relative',
  },
  creditPackCardBest: {
    borderColor: colors.amber,
    borderWidth: 1.5,
    backgroundColor: '#1C160F',
  },
  creditBadgeWrap: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  creditTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#fff',
  },
  creditDesc: {
    fontSize: 11,
    color: colors.textSecondary,
    marginTop: 2,
    paddingRight: 60,
  },
  creditPrice: {
    fontSize: 15,
    fontWeight: '700',
    color: '#fff',
  },
  creditActionBtn: {
    backgroundColor: colors.surfaceMuted,
    height: 38,
    borderRadius: radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    marginTop: 4,
  },
  creditActionBtnText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 13,
  },
  saveTag: {
    position: 'absolute',
    top: -10,
    right: 15,
    backgroundColor: colors.amber,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: radius.sm,
  },
  saveTagText: {
    color: '#000',
    fontSize: 10,
    fontWeight: '800',
  },

  // Stub and auxiliary screens styling
  stubContainer: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
    justifyContent: 'center',
  },
  stubTitle: {
    ...typography.h1,
    textAlign: 'center',
    marginBottom: spacing.md,
  },
  stubDetails: {
    ...typography.body,
    color: colors.textSecondary,
    textAlign: 'justify',
    lineHeight: 24,
  },
  stubCloseBtn: {
    backgroundColor: colors.amber,
    height: 48,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: spacing.lg,
  },
  stubCloseBtnText: {
    color: '#000',
    fontWeight: '700',
    fontSize: 16,
  },

  infoContentContainer: {
    paddingBottom: spacing.lg,
  },
  infoSectionHeader: {
    ...typography.h2,
    fontSize: 14,
    color: colors.amber,
    fontWeight: '700',
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  infoBodyText: {
    ...typography.body,
    color: colors.textSecondary,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'justify',
    marginBottom: spacing.md,
  },

  // Game Styling
  gameScoreText: {
    ...typography.caption,
    textAlign: 'center',
    color: colors.amber,
    fontWeight: '700',
    marginBottom: spacing.lg,
  },
  gameBoxCard: {
    backgroundColor: colors.surface,
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.border,
    minHeight: 140,
    justifyContent: 'center',
    gap: spacing.sm,
    marginBottom: spacing.xl,
  },
  gameLabel: {
    ...typography.bodyBold,
    fontSize: 16,
    color: '#fff',
  },
  gameSub: {
    ...typography.caption,
    color: colors.textSecondary,
    lineHeight: 20,
  },
  gameActionRow: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  gameOptionBtn: {
    flex: 1,
    height: 52,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gameOptionText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 15,
  },

  // Premium Caliber Game Screen Overhaul Styles
  gameContainer: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  gameContent: {
    padding: spacing.md,
    gap: spacing.md,
    paddingBottom: spacing.xxl,
  },
  gameHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: spacing.md,
    position: 'relative',
  },
  gameCloseBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  gameHeaderTitle: {
    ...typography.h2,
    color: '#fff',
    textAlign: 'center',
  },
  gameHeaderSubtitle: {
    ...typography.caption,
    color: colors.amber,
    letterSpacing: 2,
    textAlign: 'center',
  },
  gameWatchHeaderSection: {
    alignItems: 'center',
    marginVertical: spacing.md,
  },
  watchDialOuterRing: {
    width: 140,
    height: 140,
    borderRadius: 70,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    shadowColor: colors.amber,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  gameStatsHudRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    width: '100%',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    backgroundColor: 'rgba(30, 24, 20, 0.95)',
    marginVertical: spacing.md,
  },
  hudStatBox: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  hudStatLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.textSecondary,
    letterSpacing: 0.5,
    marginRight: 4,
  },
  hudStatValue: {
    fontSize: 12,
    fontWeight: '900',
    color: '#FFF',
    letterSpacing: 0.5,
  },
  gameProgressRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginTop: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  gameProgressText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
  },
  gameProgressCounter: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.amber,
  },
  gameStepIndicatorRow: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginTop: spacing.sm,
  },
  gameStepDot: {
    width: 12,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
  },
  gameStepDotActive: {
    backgroundColor: colors.amber,
  },
  gameStepDotCompleted: {
    backgroundColor: colors.success,
  },
  gameWatchInfoCard: {
    padding: spacing.md,
    borderRadius: radius.md,
    overflow: 'hidden',
    marginVertical: spacing.sm,
    backgroundColor: 'rgba(30, 18, 10, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(236, 200, 122, 0.15)',
  },
  gameWatchInfoHead: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  gameWatchTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: '#fff',
  },
  gameWatchSubtitle: {
    fontSize: 11,
    color: colors.textSecondary,
  },
  comparisonGridRow: {
    gap: spacing.md,
    marginVertical: spacing.sm,
  },
  caliberHalfCard: {
    padding: spacing.md,
    borderRadius: radius.lg,
    overflow: 'hidden',
    gap: spacing.sm,
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
  },
  caliberCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  caliberCardTitle: {
    fontSize: 14,
    fontWeight: '800',
    color: '#fff',
  },
  caliberSpecList: {
    gap: 4,
    marginVertical: 4,
  },
  caliberBulletText: {
    fontSize: 12,
    color: '#ECE5D8',
    lineHeight: 18,
  },
  caliberSelectBtn: {
    height: 40,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    marginTop: spacing.xs,
  },
  caliberSelectBtnText: {
    color: '#000',
    fontSize: 13,
    fontWeight: '900',
  },
  gameHelperCard: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255, 255, 255, 0.02)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    padding: spacing.md,
    borderRadius: radius.md,
    marginTop: spacing.sm,
  },
  gameHelperText: {
    flex: 1,
    fontSize: 11,
    color: colors.textMuted,
    lineHeight: 16,
    textAlign: 'justify',
  },
  gameTimerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(236, 200, 122, 0.15)',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginVertical: spacing.xs,
  },
  gameTimerText: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.amber,
    letterSpacing: 1,
  },
  hintBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ECC87A',
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: radius.md,
    marginVertical: spacing.xs,
  },
  hintBtnText: {
    color: '#000',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  hintCard: {
    padding: spacing.md,
    borderRadius: radius.md,
    borderWidth: 1.5,
    borderColor: 'rgba(236, 200, 122, 0.35)',
    backgroundColor: 'rgba(30, 24, 20, 0.65)',
    marginVertical: spacing.xs,
    overflow: 'hidden',
  },
  hintText: {
    fontSize: 12,
    color: '#ECE5D8',
    lineHeight: 18,
    fontStyle: 'italic',
  },
  resultOverlayCard: {
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: 'rgba(236, 200, 122, 0.3)',
    backgroundColor: 'rgba(15, 12, 10, 0.98)',
    marginVertical: spacing.md,
    overflow: 'hidden',
    gap: spacing.md,
  },
  resultCardHeader: {
    alignItems: 'center',
    borderWidth: 1.5,
    borderRadius: radius.md,
    padding: spacing.md,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  resultCardTitle: {
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 1,
    marginBottom: 6,
  },
  resultCardSub: {
    fontSize: 12,
    color: colors.textSecondary,
    textAlign: 'center',
    lineHeight: 18,
    paddingHorizontal: spacing.sm,
  },
  resultScoreContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.03)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.05)',
    padding: spacing.md,
    borderRadius: radius.md,
  },
  resultScoreValue: {
    fontSize: 14,
    fontWeight: '900',
    color: colors.amber,
  },
  speedBonusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: radius.sm,
    overflow: 'hidden',
  },
  speedBonusText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#000',
    letterSpacing: 0.5,
  },
  explanationSection: {
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
    borderWidth: 1,
    borderColor: 'rgba(236, 200, 122, 0.15)',
    padding: spacing.md,
    borderRadius: radius.md,
  },
  explanationTitle: {
    fontSize: 12,
    fontWeight: '900',
    color: colors.amber,
    letterSpacing: 0.8,
  },
  explanationText: {
    fontSize: 12,
    color: '#ECE5D8',
    lineHeight: 18,
    textAlign: 'justify',
  },
  gameContinueBtn: {
    height: 48,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
    marginTop: spacing.sm,
  },
  gameContinueBtnText: {
    color: '#000',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
  },
  scoreboardContainer: {
    flex: 1,
    backgroundColor: '#0A0805',
  },
  scoreboardHeaderTitle: {
    fontSize: 22,
    fontWeight: '900',
    color: '#fff',
    letterSpacing: 1,
    textAlign: 'center',
    marginTop: spacing.xs,
  },
  scoreboardHeaderSubtitle: {
    fontSize: 10,
    color: colors.amber,
    fontWeight: '800',
    letterSpacing: 2,
    textAlign: 'center',
  },
  scoreboardMetricsCard: {
    width: '100%',
    padding: spacing.lg,
    borderRadius: radius.lg,
    borderWidth: 1.5,
    borderColor: 'rgba(236, 200, 122, 0.25)',
    backgroundColor: 'rgba(30, 24, 20, 0.4)',
    alignItems: 'center',
    overflow: 'hidden',
    marginVertical: spacing.md,
  },
  rankCard: {
    width: '100%',
    padding: spacing.md,
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(236, 200, 122, 0.15)',
    alignItems: 'center',
    overflow: 'hidden',
  },
  rankTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: colors.amber,
    letterSpacing: 0.5,
    marginBottom: 6,
    textAlign: 'center',
  },
  rankDesc: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 18,
    textAlign: 'center',
  },
  returnVaultBtn: {
    height: 48,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.25)',
    backgroundColor: 'transparent',
  },
  returnVaultBtnText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 1,
  },
});
